language: ruby
gemfile: Gemfile.ci

before_install:
 - gem update --system 2.2.1
 - gem --version
 - gem install bundler

rvm:
  - ruby-head
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ree